"""
Central configuration using pydantic-settings.
All settings can be overridden via environment variables or .env file.
"""

from functools import lru_cache
from pathlib import Path
from typing import Literal

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    # ── Application ─────────────────────────────────────────────────────────
    app_name: str = "Athar.AI"
    app_version: str = "3.0.0"
    debug: bool = False
    environment: Literal["development", "production", "test"] = "development"

    # ── API ─────────────────────────────────────────────────────────────────
    api_host: str = "0.0.0.0"
    api_port: int = 8000
    allowed_origins: list[str] = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:3001",
    ]

    # ── LLM Provider ────────────────────────────────────────────────────────
    # Priority: groq → ollama → huggingface
    llm_provider: Literal["groq", "ollama", "huggingface", "auto"] = "auto"

    # Groq (free tier, highly recommended)
    groq_api_key: str = ""
    groq_model: str = "llama-3.3-70b-versatile"

    # Ollama (local, great for privacy)
    ollama_base_url: str = "http://localhost:11434"
    ollama_model: str = "llama3.2"

    # HuggingFace (always available, slowest)
    hf_model: str = "google/flan-t5-base"
    hf_device: int = -1  # -1 = CPU, 0 = first GPU

    # Generation parameters
    llm_temperature: float = 0.2
    llm_max_tokens: int = 1024
    llm_timeout: int = 60

    # ── Embeddings ──────────────────────────────────────────────────────────
    embedding_model: str = "sentence-transformers/all-MiniLM-L6-v2"
    embedding_device: str = "cpu"  # "cpu" or "cuda"

    # ── Retrieval ───────────────────────────────────────────────────────────
    retrieval_top_k: int = 6          # candidates before reranking
    retrieval_final_k: int = 3        # after reranking
    bm25_weight: float = 0.4          # RRF weight for BM25
    semantic_weight: float = 0.6      # RRF weight for semantic
    min_similarity: float = 0.1       # minimum score threshold

    # ── Chunking ────────────────────────────────────────────────────────────
    chunk_size: int = 600
    chunk_overlap: int = 100

    # ── Vector Database ──────────────────────────────────────────────────────
    chroma_persist_dir: str = "./chroma_db"
    # Versioned because vectors generated by prior implementations are not
    # compatible with the stable embedding profiles used by this release.
    chroma_collection: str = "athar_heritage_v1"

    # ── Data ─────────────────────────────────────────────────────────────────
    data_dir: str = "./data/raw"
    max_wikipedia_articles: int = 40

    # ── Logging ──────────────────────────────────────────────────────────────
    log_level: str = "INFO"
    log_format: Literal["json", "pretty"] = "pretty"

    # ── Rate Limiting ─────────────────────────────────────────────────────────
    rate_limit_requests: int = 30     # per minute
    rate_limit_window: int = 60       # seconds

    # ── Conversation ─────────────────────────────────────────────────────────
    max_conversation_turns: int = 10  # history turns to keep
    conversation_ttl_hours: int = 24  # how long to keep in memory


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Return cached settings instance."""
    return Settings()


# Convenience alias
settings = get_settings()

# Resolve paths relative to project root
# ``config.py`` lives in backend/src/athar; three parents up is the repository
# root.  Resolve all persisted artefacts from there, never from the shell CWD.
BASE_DIR = Path(__file__).resolve().parents[3]
DATA_DIR = BASE_DIR / settings.data_dir
CHROMA_DIR = BASE_DIR / settings.chroma_persist_dir
